#
# GMT 6.5.0 Defaults file
#
# COLOR Parameters
#
COLOR_MODEL                    = hsv
#
# I/O Parameters
#
IO_NC4_CHUNK_SIZE              = classic
#
# Projection Parameters
#
PROJ_LENGTH_UNIT               = inch
